<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	
	>
<channel>
	<title>Comments on: Comparison of Exception Handling in C++ and Java</title>
	<atom:link href="http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/feed/" rel="self" type="application/rss+xml" />
	<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/</link>
	<description>A computer science portal for geeks</description>
	<lastBuildDate>Tue, 17 Nov 2015 05:17:31 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.6.8</generator>
	<item>
		<title>By: srikanth</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-36940</link>
		<dc:creator><![CDATA[srikanth]]></dc:creator>
		<pubDate>Wed, 28 May 2014 06:36:00 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-36940</guid>
		<description><![CDATA[Hi ,In the 3rd point program&#039;s output it should be &quot;Got the test Exception&quot;.]]></description>
		<content:encoded><![CDATA[<p>Hi ,In the 3rd point program&#8217;s output it should be &#8220;Got the test Exception&#8221;.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: manish</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-2633</link>
		<dc:creator><![CDATA[manish]]></dc:creator>
		<pubDate>Thu, 23 Dec 2010 20:15:39 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-2633</guid>
		<description><![CDATA[thanks...No I am not Manish Jain..My name is Manish Jawa]]></description>
		<content:encoded><![CDATA[<p>thanks&#8230;No I am not Manish Jain..My name is Manish Jawa</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Venki</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-2632</link>
		<dc:creator><![CDATA[Venki]]></dc:creator>
		<pubDate>Thu, 23 Dec 2010 16:39:25 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-2632</guid>
		<description><![CDATA[Is it Manish Jain? Good explanation. Thanks.]]></description>
		<content:encoded><![CDATA[<p>Is it Manish Jain? Good explanation. Thanks.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Manish</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-2631</link>
		<dc:creator><![CDATA[Manish]]></dc:creator>
		<pubDate>Thu, 23 Dec 2010 15:20:02 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-2631</guid>
		<description><![CDATA[There is more to point 4 than mentioned here. There is a reason why C++ doesnt have finally , it is because it doesn&#039;t need it. Finally is required by languages in which objects dont have deterministic cleanup ie their lifetime is not determined by scope. In Java objects are garbage-collected so their life-time is indeterministic with respect to their scope.If an exception occurs and object goes out of scope , no gurantees can be made about its cleanup-time.If that object encapsulates a scarce resource , this means that no gurantee can be placed on cleanup of that scarce resource , which is bad. So in Java we have finally block you can free the underlying native resource as the object goes out-of-scope. Compiler gaurantees that finally block will always be called. In C++ on the other hand for auto variables we have lifetime determined by scope and so if we  create the object on stack as local compiler gurantees its cleanup as soon as object goes out of scope. This technique is also called RAII.]]></description>
		<content:encoded><![CDATA[<p>There is more to point 4 than mentioned here. There is a reason why C++ doesnt have finally , it is because it doesn&#8217;t need it. Finally is required by languages in which objects dont have deterministic cleanup ie their lifetime is not determined by scope. In Java objects are garbage-collected so their life-time is indeterministic with respect to their scope.If an exception occurs and object goes out of scope , no gurantees can be made about its cleanup-time.If that object encapsulates a scarce resource , this means that no gurantee can be placed on cleanup of that scarce resource , which is bad. So in Java we have finally block you can free the underlying native resource as the object goes out-of-scope. Compiler gaurantees that finally block will always be called. In C++ on the other hand for auto variables we have lifetime determined by scope and so if we  create the object on stack as local compiler gurantees its cleanup as soon as object goes out of scope. This technique is also called RAII.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: GeeksforGeeks</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-2570</link>
		<dc:creator><![CDATA[GeeksforGeeks]]></dc:creator>
		<pubDate>Sat, 11 Dec 2010 16:32:10 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-2570</guid>
		<description><![CDATA[@Agraj: Thanks for pointing this out. We have added the above info to point 2.]]></description>
		<content:encoded><![CDATA[<p>@Agraj: Thanks for pointing this out. We have added the above info to point 2.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Agraj</title>
		<link>http://www.geeksforgeeks.org/comparison-of-exception-handling-in-c-and-java/#comment-2569</link>
		<dc:creator><![CDATA[Agraj]]></dc:creator>
		<pubDate>Sat, 11 Dec 2010 16:09:50 +0000</pubDate>
		<guid isPermaLink="false">http://geeksforgeeks.org/?p=9389#comment-2569</guid>
		<description><![CDATA[Point 2 is incorrect. In Java, for all practical purposes, you can use

catch(Exception e){
.......
}

for catch all idiom.

Coz, normally we do not catch Throwable(s) other than Exception(s) (which are Errors)]]></description>
		<content:encoded><![CDATA[<p>Point 2 is incorrect. In Java, for all practical purposes, you can use</p>
<p>catch(Exception e){<br />
&#8230;&#8230;.<br />
}</p>
<p>for catch all idiom.</p>
<p>Coz, normally we do not catch Throwable(s) other than Exception(s) (which are Errors)</p>
]]></content:encoded>
	</item>
</channel>
</rss>

<!-- Dynamic page generated in 0.042 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2017-11-24 14:12:36 -->

<!-- Compression = gzip -->